name = "star-categorizer"
compatibility_date = "2023-11-21"
compatibility_flags = ["nodejs_compat"]
main = ".vercel/output/static/_worker.js"

# Bind Environment Variables using wrangler secrets
# Run the following commands to set secrets:
#   wrangler secret put GITHUB_ACCESS_TOKEN
#   wrangler secret put ANTHROPIC_API_KEY
#   wrangler secret put GEMINI_API_KEY

# For local development with .env file
# [vars]
# GITHUB_ACCESS_TOKEN = ""
# ANTHROPIC_API_KEY = ""
# GEMINI_API_KEY = ""

# KV Namespace for caching responses
# To create a KV namespace:
#   wrangler kv:namespace create "STAR_CACHE"
[[kv_namespaces]]
binding = "STAR_CACHE"
id = "YOUR_KV_ID_HERE" # Replace with your KV namespace ID
preview_id = "YOUR_PREVIEW_KV_ID_HERE" # Replace with your preview KV namespace ID

# KV Namespace for developer catalog
# To create a KV namespace:
#   wrangler kv:namespace create "DEVELOPER_CATALOG"
[[kv_namespaces]]
binding = "DEVELOPER_CATALOG"
id = "YOUR_KV_ID_HERE" # Replace with your KV namespace ID
preview_id = "YOUR_PREVIEW_KV_ID_HERE" # Replace with your preview KV namespace ID

# Pages configuration
[site]
bucket = ".vercel/output/static"

[build]
command = "npm run wrangler:build"
